runtime: go111
automatic_scaling:
    max_idle_instances: 1
    max_concurrent_requests: 100

handlers:
    - url: /static
      static_dir: static
    - url: /.*
      script: auto
      secure: always
