name: Deploy

on:
    push:
        branches: ["master", "beta"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Extract branch name
              run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
            - name: Build release
              working-directory: web-app
              run: docker-compose run sample yarn build
            - name: Create .ssh directory
              run: mkdir $HOME/.ssh && chmod 700 $HOME/.ssh
            - name: Copy SSH key for iBrave
              run: ( echo ${{ secrets.IBRAVE_SSH_KEY }} > $HOME/.ssh/id_rsa ) && chmod 600 $HOME/.ssh/id_rsa
            - name: Sync release to iBrave
              run: rsync -a --delete web-app/ oort.se@ssh.ibrave.io:public_html/diplicity-${BRANCH_NAME}/
